// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sample.Infrastructure.Data;

#nullable disable

namespace Sample.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240116210801_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sample.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id")
                        .HasName("PK_Product_Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgUri = "https://rohlik.img/",
                            Name = "Rohlík",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 2,
                            ImgUri = "https://houska.img/",
                            Name = "Houska",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 3,
                            Description = "houskový knedlík",
                            ImgUri = "https://knedlik.img/",
                            Name = "Knedlík",
                            Price = 24.9m
                        },
                        new
                        {
                            Id = 4,
                            ImgUri = "https://vanocka.img/",
                            Name = "Vánočka",
                            Price = 49.9m
                        },
                        new
                        {
                            Id = 5,
                            ImgUri = "https://pomeranc.img/",
                            Name = "Pomeranč",
                            Price = 5m
                        },
                        new
                        {
                            Id = 6,
                            ImgUri = "https://kiwi.img/",
                            Name = "Kiwi",
                            Price = 7m
                        },
                        new
                        {
                            Id = 7,
                            ImgUri = "https://syr.img/",
                            Name = "Sýr",
                            Price = 18.9m
                        },
                        new
                        {
                            Id = 8,
                            ImgUri = "https://jogurt.img/",
                            Name = "Jogurt",
                            Price = 25.9m
                        },
                        new
                        {
                            Id = 9,
                            ImgUri = "https://salam.img/",
                            Name = "Salám",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 10,
                            ImgUri = "https://mleko.img/",
                            Name = "Mléko",
                            Price = 14.9m
                        },
                        new
                        {
                            Id = 11,
                            ImgUri = "https://paprika.img/",
                            Name = "Paprika",
                            Price = 20m
                        },
                        new
                        {
                            Id = 12,
                            ImgUri = "https://patizon.img/",
                            Name = "Patizon",
                            Price = 22m
                        });
                });

            modelBuilder.Entity("Sample.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK_User_Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Password = "4C488C654B5804093A9E6C7D5F63E3202026107F40CCF9206CAADC964D8FB8145B098B1F23D6A8D28582144A805643715BD8465ACD28BAA8AF66B8373B7C8B55E93511A7366B74E373EB2E708E19EA01F0B0A56CBB3B36AA37118F593B1E440546785B3D73DC537AEA7B9D65A4875501ADF2FA83B814245613EBE9400EAEED3A",
                            Salt = "945362B4EC31796A9785F197BCD7C6E91F3ACCFDCD67ADC6F1399E529B952BDF4EF8CEF54918A21960E9D002DE2924F9BAE0955687B55DE68F14590EFBBF8DC1EACABAAB40998D1114987B18BA6DD2C7A8C2800CB0834D8542F30C6C6EF690575FEFBFFB219D6E18FC0742BA8805A291CFE1C49F1D5D2AD1B77032B6D89C21BF",
                            Username = "test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
