// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sample.Infrastructure.Data;

#nullable disable

namespace Sample.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sample.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id")
                        .HasName("PK_Product_Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgUri = "https://rohlik.img",
                            Name = "Rohlík",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 2,
                            ImgUri = "https://houska.img",
                            Name = "Houska",
                            Price = 3.5m
                        },
                        new
                        {
                            Id = 3,
                            Description = "houskový knedlík",
                            ImgUri = "https://knedlik.img",
                            Name = "Knedlík",
                            Price = 24.9m
                        },
                        new
                        {
                            Id = 4,
                            ImgUri = "https://vanocka.img",
                            Name = "Vánočka",
                            Price = 49.9m
                        },
                        new
                        {
                            Id = 5,
                            ImgUri = "https://pomeranc.img",
                            Name = "Pomeranč",
                            Price = 5m
                        },
                        new
                        {
                            Id = 6,
                            ImgUri = "https://kiwi.img",
                            Name = "Kiwi",
                            Price = 7m
                        },
                        new
                        {
                            Id = 7,
                            ImgUri = "https://syr.img",
                            Name = "Sýr",
                            Price = 18.9m
                        },
                        new
                        {
                            Id = 8,
                            ImgUri = "https://jogurt.img",
                            Name = "Jogurt",
                            Price = 25.9m
                        },
                        new
                        {
                            Id = 9,
                            ImgUri = "https://salam.img",
                            Name = "Salám",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 10,
                            ImgUri = "https://mleko.img",
                            Name = "Mléko",
                            Price = 14.9m
                        },
                        new
                        {
                            Id = 11,
                            ImgUri = "https://paprika.img",
                            Name = "Paprika",
                            Price = 20m
                        },
                        new
                        {
                            Id = 12,
                            ImgUri = "https://patizon.img",
                            Name = "Patizon",
                            Price = 22m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
